CREATE OR REPLACE TABLE `mydata-494606.mydata.agg_dashboard_hourly` AS
SELECT
  DATE(
CASE
  WHEN REGEXP_CONTAINS(TRIM(CAST(`下注时间` AS STRING)), r'^\d+(\.\d+)?$')
       AND SAFE_CAST(TRIM(CAST(`下注时间` AS STRING)) AS FLOAT64) BETWEEN 30000 AND 60000
    THEN DATETIME_ADD(
      DATETIME '1899-12-30 00:00:00',
      INTERVAL CAST(ROUND(SAFE_CAST(TRIM(CAST(`下注时间` AS STRING)) AS FLOAT64) * 86400) AS INT64) SECOND
    )
  ELSE SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', TRIM(CAST(`下注时间` AS STRING)))
END
) AS report_date,
  EXTRACT(HOUR FROM 
CASE
  WHEN REGEXP_CONTAINS(TRIM(CAST(`下注时间` AS STRING)), r'^\d+(\.\d+)?$')
       AND SAFE_CAST(TRIM(CAST(`下注时间` AS STRING)) AS FLOAT64) BETWEEN 30000 AND 60000
    THEN DATETIME_ADD(
      DATETIME '1899-12-30 00:00:00',
      INTERVAL CAST(ROUND(SAFE_CAST(TRIM(CAST(`下注时间` AS STRING)) AS FLOAT64) * 86400) AS INT64) SECOND
    )
  ELSE SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', TRIM(CAST(`下注时间` AS STRING)))
END
) AS report_hour,
  COUNT(*) AS bet_count,
  COUNT(DISTINCT `会员账号`) AS member_count,
  SUM(SAFE_CAST(REPLACE(TRIM(CAST(`下注金额` AS STRING)), ',', '') AS FLOAT64)) AS bet_amount,
  SUM(SAFE_CAST(REPLACE(TRIM(CAST(`有效投注` AS STRING)), ',', '') AS FLOAT64)) AS valid_turnover,
  SUM(SAFE_CAST(REPLACE(TRIM(CAST(`盈亏` AS STRING)), ',', '') AS FLOAT64)) AS member_profit_loss,
  -SUM(SAFE_CAST(REPLACE(TRIM(CAST(`盈亏` AS STRING)), ',', '') AS FLOAT64)) AS platform_profit_loss,
  CURRENT_TIMESTAMP() AS updated_at
FROM `mydata-494606.mydata.fact_bet_detail`
WHERE DATE(
CASE
  WHEN REGEXP_CONTAINS(TRIM(CAST(`下注时间` AS STRING)), r'^\d+(\.\d+)?$')
       AND SAFE_CAST(TRIM(CAST(`下注时间` AS STRING)) AS FLOAT64) BETWEEN 30000 AND 60000
    THEN DATETIME_ADD(
      DATETIME '1899-12-30 00:00:00',
      INTERVAL CAST(ROUND(SAFE_CAST(TRIM(CAST(`下注时间` AS STRING)) AS FLOAT64) * 86400) AS INT64) SECOND
    )
  ELSE SAFE.PARSE_DATETIME('%Y-%m-%d %H:%M:%S', TRIM(CAST(`下注时间` AS STRING)))
END
) IS NOT NULL
GROUP BY report_date, report_hour;
